export const OperationNames = {
  adapter: 'adapter',
  url: 'url',
  path: 'path',
  query: 'query',
  headers: 'headers',
  body: 'body',
  method: 'method',
  mimeType: 'mimeType',
  statusCode: 'statusCode',
  requestHeaders: 'requestHeaders',
  responseHeaders: 'responseHeaders',
  requestBody: 'requestBody',
  requestUrl: 'requestUrl',
  rawRequest: 'rawRequest',
  rawResponse: 'rawResponse',
  responseBody: 'responseBody',

  getPath: 'getPath',
  getQuery: 'getQuery',
  getUrl: 'getUrl',
  getRequestHeaders: 'getRequestHeaders',
  getResponseHeaders: 'getResponseHeaders',
  getRequestBody: 'getRequestBody',
  getResponseBody: 'getResponseBody',
  getMimeType: 'getMimeType',
  getStatusCode: 'getStatusCode',
  request: 'request',
}
