export const OperationDefaultLocals = {
  adapter: 'adapter',
  url: 'url',
  path: 'path',
  query: 'query',
  headers: 'headers',
  body: 'body',
  cookies: 'cookies',
  method: 'method',
  mimeType: 'mimeType',
  statusCode: 'statusCode',
  request: 'request',
  requestHeaders: 'requestHeaders',
  responseHeaders: 'responseHeaders',
  requestBody: 'requestBody',
  requestUrl: 'requestUrl',
  rawRequest: 'rawRequest',
  rawResponse: 'rawResponse',
  responseBody: 'responseBody',
  responseCookies: 'responseCookies',
}
