import fetch from 'node-fetch'
import {
  generate,
  nameProviders,
  pathProviders,
  validator,
  writer,
  reader,
  prettierStringify,
  presets,
} from '@oats-ts/openapi'
import { promises as fs } from 'fs'
import { join, parse } from 'path'

const REPO = 'oats-ts/oats-schemas'
const PATH = 'src/generated'

type FileDescriptor = {
  path: string
  mode: string
  type: 'tree' | 'blob'
  sha: string
  size: number
  url: string
}

export async function getFiles(folders: string[]): Promise<string[]> {
  const response = await fetch(`https://api.github.com/repos/${REPO}/git/trees/master?recursive=true`)
  const tree = ((await response.json()) as any).tree as FileDescriptor[]
  return tree
    .filter((file) => file.type !== 'tree')
    .filter((file) => folders.some((folder) => file.path.startsWith(`${folder}/`)))
    .filter((file) => file.path.endsWith('.json'))
    .map((file) => file.path)
}

function getSchemaUrl(path: string): string {
  return `https://raw.githubusercontent.com/${REPO}/master/${path}`
}

function getCodePath(path: string): string {
  return join(PATH, `${parse(path).name}.ts`)
}

export async function generateCode(path: string) {
  const codePath = getCodePath(path)
  const url = getSchemaUrl(path)
  return generate({
    configuration: {
      log: true,
      name: nameProviders.default(),
      path: pathProviders.singleFile(codePath),
    },
    validator: validator(),
    reader: reader({ path: url }),
    generators: presets.fullStack({
      'json-schema/type-guard': {
        ignore: (schema: any) => Boolean(schema?.['x-ignore-validation']),
      },
      'json-schema/type-validator': {
        ignore: (schema: any) => Boolean(schema?.['x-ignore-validation']),
      },
    }),
    writer: writer({
      comments: {
        leadingComments: [
          {
            type: 'block',
            text: `This file has been generated by Oats, please don't modify it by hand!\n\nGenerated from ${url}`,
          },
        ],
      },
      stringify: prettierStringify({
        parser: 'typescript',
        arrowParens: 'always',
        printWidth: 120,
        semi: false,
        singleQuote: true,
        trailingComma: 'all',
      }),
    }),
  })
}

async function generateAll() {
  await fs.rm(PATH, { force: true, recursive: true })
  const files = await getFiles(['schemas', 'generated-schemas'])
  for (const path of files) {
    console.log(`===\n${path}\n===`)
    await generateCode(path)
  }
}

generateAll()
