import fetch from 'node-fetch'
import { promises as fs } from 'fs'
import { join, parse } from 'path'
import { generate } from '@oats-ts/oats'
import {
  formatters,
  validator,
  readers,
  writers,
  presets,
  nameProviders,
  pathProviders,
  generator,
} from '@oats-ts/openapi'

const REPO = 'oats-ts/oats-schemas'
const PATH = 'src/generated'

type FileDescriptor = {
  path: string
  mode: string
  type: 'tree' | 'blob'
  sha: string
  size: number
  url: string
}

export async function getFiles(folders: string[]): Promise<string[]> {
  const response = await fetch(`https://api.github.com/repos/${REPO}/git/trees/master?recursive=true`)
  const tree = ((await response.json()) as any).tree as FileDescriptor[]
  return tree
    .filter((file) => file.type !== 'tree')
    .filter((file) => folders.some((folder) => file.path.startsWith(`${folder}/`)))
    .filter((file) => file.path.endsWith('.json'))
    .map((file) => file.path)
}

function getSchemaUrl(path: string): string {
  return `https://raw.githubusercontent.com/${REPO}/master/${path}`
}

function getCodePath(path: string): string {
  return join(PATH, `${parse(path).name}.ts`)
}

export async function generateCode(path: string) {
  const codePath = getCodePath(path)
  const url = getSchemaUrl(path)
  try {
    await generate({
      validator: validator(),
      reader: readers.https.json(url),
      generator: generator({
        nameProvider: nameProviders.default(),
        pathProvider: pathProviders.singleFile(codePath),
      })(
        presets.fullStack({
          overrides: {
            'json-schema/type-guard': {
              ignore: (schema: any) => Boolean(schema?.['x-ignore-validation']),
            },
            'json-schema/type-validator': {
              ignore: (schema: any) => Boolean(schema?.['x-ignore-validation']),
            },
          },
        }),
      ),
      writer: writers.typescript({
        format: formatters.prettier({
          parser: 'typescript',
          arrowParens: 'always',
          printWidth: 120,
          semi: false,
          singleQuote: true,
          trailingComma: 'all',
        }),
        comments: {
          leadingComments: [
            {
              type: 'block',
              text: `This file has been generated by Oats, please don't modify it by hand!\n\nGenerated from ${url}`,
            },
          ],
        },
      }),
    })
    console.log('ok', codePath, url)
  } catch (e) {
    console.error(codePath, url)
    console.error('thrown', e, typeof e)
  }
}

async function generateAll() {
  await fs.rm(PATH, { force: true, recursive: true })
  // const files = await getFiles(['schemas', 'generated-schemas'])
  const files = [
    // 'generated-schemas/bodies.json',
    // 'generated-schemas/methods.json',
    // 'generated-schemas/parameters.json',
    // 'schemas/book-store.json',
    // 'schemas/optional-request-body.json',
    'schemas/array-schemas.json',
    'schemas/const-schemas.json',
    'schemas/discriminated-union-type-schemas.json',
    'schemas/enum-schemas.json',
    'schemas/ignored-schemas.json',
    'schemas/object-schemas.json',
    'schemas/primitive-schemas.json',
    'schemas/record-schemas.json',
    'schemas/reference-target-schema.json',
    'schemas/references.json',
    'schemas/remote-ref-schemas.json',
    'schemas/tuple-schemas.json',
    'schemas/union-type-schemas.json',
  ]
  console.log(files)
  for (const path of files) {
    console.log(`===\n${path}\n===`)
    await generateCode(path)
  }
}

generateAll()
