export type { TypeScriptWriterConfig, CommentsConfig, CommentConfig, CommentType } from './typings'
export { prettierFormatter } from './prettierFormatter'
export { defaultCommentsConfig } from './defaults/defaultCommentsConfig'
export { writer } from './writer'
export { defaultWrite } from './defaults/defaultWrite'
