import { generate } from '@oats-ts/oats-ts'
import {
  formatters,
  validator,
  readers,
  writers,
  presets,
  nameProviders,
  pathProviders,
  generator,
  loggers,
} from '@oats-ts/openapi'
import { REPO } from './constants'
import { importReplacers, localNameProviders, overrides, presetConfigs } from './overrides'
import { LoadMethod } from './typings'

export async function generateFromOpenAPIDocument(
  path: string,
  url: string,
  codePath: string,
  reader: LoadMethod,
  pathProviderKind: Exclude<keyof typeof pathProviders, 'delegating'>,
) {
  try {
    await generate({
      plugins: [loggers.simple()],
      validator: validator(),
      reader: readers[reader].mixed(url),
      generator: generator({
        nameProvider: nameProviders.default(),
        pathProvider: pathProviders[pathProviderKind](codePath),
        importReplacer: importReplacers[path],
        localNameProvider: localNameProviders[path],
        children: presets.fullStack(presetConfigs[path] ?? {}).override(overrides[path] ?? {}),
      }),
      writer: writers.typescript.file({
        format: formatters.prettier({
          parser: 'typescript',
          arrowParens: 'always',
          printWidth: 120,
          semi: false,
          singleQuote: true,
          trailingComma: 'all',
        }),
        comments: {
          leadingComments: [
            {
              type: 'block',
              text: `This file has been generated by Oats, please don't modify it by hand!\n\nGenerated from ${path} (originating from ${REPO})`,
            },
          ],
        },
      }),
    })
  } catch (e) {
    console.error(codePath, url)
    console.error('thrown', e, typeof e)
  }
}
