export const OperationDefaultLocals = {
  adapterParameter: 'adapter',
  adapterProperty: 'adapter',
  // TODO remove
  adapter: 'adapter',
  url: 'url',
  path: 'path',
  query: 'query',
  headers: 'headers',
  body: 'body',
  cookies: 'cookies',
  method: 'method',
  mimeType: 'mimeType',
  statusCode: 'statusCode',
  unusedRequest: '_request',
  request: 'request',
  requestHeaders: 'requestHeaders',
  responseHeaders: 'responseHeaders',
  requestBody: 'requestBody',
  requestUrl: 'requestUrl',
  responseBody: 'responseBody',
  responseCookies: 'responseCookies',

  rawRequest: 'rawRequest',
  rawResponse: 'rawResponse',
  typedResponse: 'typedResponse',

  getUrl: 'getUrl',
  getRequestMethod: 'getRequestMethod',
  getRequestBody: 'getRequestBody',
  getRequestHeaders: 'getRequestHeaders',

  getMimeType: 'getMimeType',
  getStatusCode: 'getStatusCode',
  getResponseBody: 'getResponseBody',
  getResponseHeaders: 'getResponseHeaders',
  getResponseCookies: 'getResponseCookies',
}
